version: 6.0.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}' 
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
branches:
  only:
    - master

image: Visual Studio 2019

configuration: Release

before_build:
  - nuget restore WpfToolkit\WPFToolkit.sln

build:
  project: 'WpfToolkit\WPFToolkit.sln'

test: off

artifacts:
  - path: '**\bin\$(configuration)\net40\DotNetProjects.*.dll'
  - path: '**\bin\$(configuration)\net40\DotNetProjects.*.pdb'
  - path: '**\bin\$(configuration)\DotNetProjects.*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: 88aMSx9ONm6ZEyZHiWughpXbF3QGPuYy7yjQxQSt69pDc89aKMBYm8KPOaCIUX9s
  artifact: /.*\.nupkg/
